### ISSUE TITLE
ImportError: No module named 'keras_en_parser_and_analyzer.library.classifiers'

### ISSUE THREAD

**Issue by matt212** [chen0040/keras-english-resume-parser-and-analyzer#2]
Hi, 
my 
current python version: 3.5.3 
Current O.S: Win 8.1
and when i download the git and run 
`python setup.py install `
everything is installed properly 
and i placed sample pdf in data/resume_samples/ and   when i execute 
`python ./demo/create_training_data.py`
I get below error !
![baseissue](https://user-images.githubusercontent.com/1698139/40471388-2b275a74-5f54-11e8-8468-1db1d6904c27.png)
any pointers on same

**Comment by matt212** [comment]
Hi, 
ok i understand the classifiers folder was not present on that path . i placed folder and this error was gone 
but my question why it was referring from Appdata folder rather than actual project folder ?
another error crop up which require to install docx after installing the docx and executing below command 
`python ./demo/create_training_data.py`
i am getting this error 

![baseissue1](https://user-images.githubusercontent.com/1698139/40472681-ca4b8a64-5f57-11e8-83a5-7b0233cf7152.png)

I resolved this issue by going to and downloading 
`python_docx‑0.8.6‑py2.py3‑none‑any.whl` from http://www.lfd.uci.edu/~gohlke/pythonlibs/
and resolves the whole issue now it is working expected

**Comment by swaup3275** [comment]
I am getting this error while running                 python create_training_data.py

Traceback (most recent call last):
  File "create_training_data.py", line 7, in <module>
    from keras_en_parser_and_analyzer.library.dl_based_parser import line_types, line_labels
  File "/usr/local/lib/python2.7/dist-packages/keras_en_parser_and_analyzer-0.0.1-py2.7.egg/keras_en_parser_and_analyzer/library/dl_based_parser.py", line 2, in <module>
    from keras_en_parser_and_analyzer.library.classifiers.lstm import WordVecBidirectionalLstmSoftmax
ImportError: No module named classifiers.lstm
