### ISSUE TITLE
ModuleNotFoundError: No module named 'exceptions'

### ISSUE THREAD

**Issue by Vaseekaran-V** [chen0040/keras-english-resume-parser-and-analyzer#21]
Hi,

When running the create_training_data.py, got this error. I came across a closed issue [similar to this](https://github.com/chen0040/keras-english-resume-parser-and-analyzer/issues/2), and tried that step, but that step is specified for windows, whereas I am using macos.

Would really appreciate if there is a solution to this, or a pointer if I missed anything.

MacOS: BigSur
Python: 3.7.6

<img width="1537" alt="Screenshot 2020-12-11 at 11 57 18" src="https://user-images.githubusercontent.com/50804222/101870848-70538b80-3ba8-11eb-8856-a438203ca3a0.png">

Thank you.

**Comment by saipavanmeruga** [comment]
Try doing pip install python-docx

**Comment by Vaseekaran-V** [comment]
@saipavanmeruga Thank you, it is working now.
